### ISSUE TITLE
Peer to peer code  review 

### ISSUE THREAD

**Issue by youmari** [Buyaki01/js_capstone_project#25]
### Hello @Buyaki01  and @vic778, great job you are doing so far in this project. 

-  I know that project is still in development but I noticed that the likes don't work can you check it.

#### TO HIGHLIGHT:
- Your repo is professional
- Well structured files
- a great job working on setup the config files

**Comment by vic778** [comment]
hi @youmari 

thank you :hand:

**Comment by Tumworobere** [comment]
Hello, @Buyaki01 and @vic778  you are doing great work so far. Keep it up!

Just work on the likes as requested by @youmari .
Happy coding!
